In [56]:
import pandas as pd
import numpy as np
import os
import ast

In [57]:
path = "../csvfile/train_labels.csv"
df = pd.read_csv(path)
df.head()

,file_name,height,width,bbox,age,race,masked,skintone,emotion,gender
0,100013282.jpg,1333,2000,"[934.0000000000097, 144.82228672769534, 238.24...",20-30s,Caucasian,unmasked,mid-light,Neutral,Male
1,100016175.jpg,1333,2000,"[1094.0513571635438, 422.91772295627203, 55.45...",20-30s,Caucasian,unmasked,light,Neutral,Male
2,10004189.jpg,2000,1333,"[419.93871061403877, 269.1250391680045, 377.19...",20-30s,Mongoloid,unmasked,light,Happiness,Female
3,100104575.jpg,1333,2000,"[1490.6909678848915, 676.0000000000097, 37.553...",20-30s,Caucasian,unmasked,mid-light,Neutral,Male
4,100104600.jpg,2000,1333,"[549.169724453414, 92.52040334013152, 306.8821...",20-30s,Caucasian,unmasked,mid-light,Happiness,Female

In [58]:
df['bbox'] = df['bbox'].apply(ast.literal_eval)

def sort_by_bbox(group):
    group['first_bbox_value'] = group['bbox'].apply(lambda x: x[0])
    return group.sort_values(by='first_bbox_value')

df_sorted = df.groupby('file_name').apply(sort_by_bbox).reset_index(drop=True)
df_sorted = df_sorted.drop(columns= ['first_bbox_value'])

In [59]:
bbox = df_sorted[df_sorted['file_name'] == 'cr_14.jpg']
bbox

Empty DataFrame
Columns: [file_name, height, width, bbox, age, race, masked, skintone, emotion, gender]
Index: []

In [60]:
df_sorted.to_csv(path, index= False)